from botocore.exceptions import EventStreamError
from boto3.session import Session
from botocore.config import Config

import streamlit as st

from langchain_core.messages import HumanMessage, SystemMessage
from langchain_community.chat_models import BedrockChat

import time
import random
import base64


def invoke_model(model, messages, data_placeholder=None):
    """
    Invokes Amazon Bedrock Foundational model.

    Args:
        model(langchain_community.chat_models.bedrock.BedrockChat): Langchain bedrock chat instance.
        messages (list): List of Langchain SystemMessage and HumanMessage objects.
        data_placeholder (instanceof st.empty): Placeholder to stream the output.
    Returns:
        str: The response or output generated by the model.
    """
    cfn_code = str()
    for chunk in model.stream(messages):
        cfn_code += chunk.content
        if data_placeholder:
            with data_placeholder.container():
                st.write(cfn_code)
    return cfn_code


def backoff_mechanism(func, model, messages, data_placeholder=None):
    """
    Implements a backoff mechanism to handle throttling exceptions.

    Args:
        func (function): The function to be called with backoff.
        model (langchain_community.chat_models.bedrock.BedrockChat): Langchain bedrock chat instance.
        messages (list): List of Langchain SystemMessage and HumanMessage objects.
        data_placeholder (instanceof st.empty): Placeholder to stream the output.

    Returns:
        str: The response or output generated by the model.
    """
    MAX_RETRIES = 5  # Maximum number of retries
    INITIAL_DELAY = 1  # Initial delay in seconds
    MAX_DELAY = 60  # Maximum delay in second

    delay = INITIAL_DELAY
    retries = 0

    while retries < MAX_RETRIES:
        try:
            return func(
                model=model, messages=messages, data_placeholder=data_placeholder
            )
        except EventStreamError as e:
            print(f"Retry {retries + 1}/{MAX_RETRIES}: {e}")
            time.sleep(delay + random.uniform(0, 1))  # Add a random jitter
            delay = min(delay * 2, MAX_DELAY)
            retries += 1


class Bedrock:
    """
    Amazon Bedrock class to invoke Foundational Models. This class is used to generate AWS architecture explaination from architecture image.

    Usage:

    bedrock = Bedrock(inference_params=inference_params)

    # Generates the explaination of architecture diagram and streams the output to streamlit app.
    explain= bedrock.invoke_explain_model(image,image_type,explain_placeholder,)

    # Reset the session.
    bedrock.new_session()

    The class initializes session state on first run. It reuses the session for subsequent calls for continuity.
    """

    def __init__(self, inference_params):

        if "BEDROCK_RUNTIME_CLIENT" not in st.session_state:

            st.session_state["BEDROCK_RUNTIME_CLIENT"] = Session().client(
                "bedrock-runtime", config=Config(read_timeout=600)
            )
        self._inference_params = inference_params

        self._explain_prompt = """
            You are an AWS Certified Solutions Architect with extensive experience in interpreting and explaining AWS Architecture diagrams. Given an architecture diagram as input, your task is to provide a detailed, step-by-step description of the components and their interactions within the architecture.

            When describing the architecture, follow these guidelines:

            1. Identify the main components and services depicted in the diagram.
            2. Explain the flow of data and requests through the architecture, starting from the client or user interface and tracing the path through various components.
            3. Describe the purpose and role of each component in the architecture, highlighting its responsibilities and how it contributes to the overall system.

            Output the explanation in a concise and understandable format.
            """

        self._sys_explain_prompt = "Your goal is to provide a concise and easily understandable step-by-step explaination of the AWS Architecture diagram. Skip the preamble."

    def get_explain_messages(self, image, image_type):
        """
        Returns the messages for the explain model.
        Args:
            image (BytesIO): The image to explain.
            image_type (str): The type of the image.
        Returns:
            list: The list of messages.
        """
        human_message = [
            {"type": "text", "text": self._explain_prompt},
            {
                "type": "image",
                "source": {
                    "type": "base64",
                    "media_type": image_type,
                    "data": base64.b64encode(image.getvalue()).decode("utf-8"),
                },
            },
        ]

        return [
            SystemMessage(content=self._sys_explain_prompt),
            HumanMessage(content=human_message),
        ]

    def invoke_explain_model(self, image, image_type, data_placeholder):
        """
        Invokes the explain model.
        Args:
            image (BytesIO): The image to explain.
            image_type (str): The type of the image.
            data_placeholder (instanceof st.empty): Placeholder to stream the output.
        Returns:
            str: The response or output generated by the model.
        """
        explain_model = self.get_llm()

        messages = self.get_explain_messages(image, image_type)

        explain = backoff_mechanism(
            func=invoke_model,
            model=explain_model,
            messages=messages,
            data_placeholder=data_placeholder,
        )
        return explain

    def get_llm(
        self, model_id="anthropic.claude-3-sonnet-20240229-v1:0", streaming=True
    ):
        """
        Returns the LLM instance.
        Args:
            model_id (str): The ID of the model.
            streaming (bool): Whether to use streaming.
        Returns:
            langchain_community.chat_models.bedrock.BedrockChat: The LLM instance.
        """
        model_kwargs = {
            "max_tokens": 4096,
            "temperature": self._inference_params["temperature"],
            "top_k": self._inference_params["top_k"],
            "top_p": self._inference_params["top_p"],
            "stop_sequences": ["\n\nHuman:"],
        }

        return BedrockChat(
            model_id=model_id,
            model_kwargs=model_kwargs,
            client=st.session_state["BEDROCK_RUNTIME_CLIENT"],
            streaming=streaming,
        )

    def new_session(self):
        """
        Resets the session.
        """
        del st.session_state["BEDROCK_RUNTIME_CLIENT"]
