import sys
from pip._internal import main

main(
    [
        "install",
        "-I",
        "-q",
        "boto3",
        "--target",
        "/tmp/",
        "--no-cache-dir",
        "--disable-pip-version-check",
    ]
)
sys.path.insert(0, "/tmp/")

from botocore.exceptions import ClientError, ValidationError
from boto3.session import Session

import random
import time
import os
import datetime

KnowledgeBaseId = os.environ["KnowledgeBaseId"]
EnvironmentName = os.environ["EnvironmentName"]
summary_modelId = "anthropic.claude-3-haiku-20240307-v1:0"
generate_modeId = "anthropic.claude-3-sonnet-20240229-v1:0"

bedrock = Session().client("bedrock-runtime")
cfn = Session().client("cloudformation")
bedrock_agent = Session().client("bedrock-agent-runtime")
s3 = Session().client("s3")
table = Session().resource("dynamodb").Table(f"templatestorage-atc-{EnvironmentName}")


############################
##### Invoke Bedrock ######
##########################
def invoke_model(modelId, system_prompt, messages):
    """
    Invokes Amazon Bedrock Foundational model.

    Args:
        modelId (str): The ID or name of the foundational model to be invoked.
        system_prompt (str): The prompt or instruction to be provided to the model, setting the context or guiding the model's behavior.
        messages (list): A list of messages or input data to be processed by the model.

    Returns:
        str: The response or output generated by the model.
    """

    response = bedrock.converse(
        modelId=modelId,
        messages=messages,
        system=[{'text': system_prompt}],
        inferenceConfig={'temperature': 0.0, 'maxTokens': 4000},
        )
    return response["output"]["message"]["content"][0]["text"]


def backoff_mechanism(func, modelId, system_prompt, messages):
    """
    Implements a backoff mechanism to handle throttling exceptions.

    Args:
        func (function): The function to be called with backoff.
        modelId (str): The ID or name of the foundational model to be invoked.
        system_prompt (str): The prompt or instruction to be provided to the model, setting the context or guiding the model's behavior.
        messages (list): A list of messages or input data to be processed by the model.

    Returns:
        str: The response or output generated by the model.
    """
    MAX_RETRIES = 5  # Maximum number of retries
    INITIAL_DELAY = 1  # Initial delay in seconds
    MAX_DELAY = 60  # Maximum delay in second

    delay = INITIAL_DELAY
    retries = 0

    while retries < MAX_RETRIES:
        try:
            return func(modelId=modelId, system_prompt=system_prompt, messages=messages)
        except bedrock.exceptions.ThrottlingException as e:
            print(f"Retry {retries + 1}/{MAX_RETRIES}: {e}")
            time.sleep(delay + random.uniform(0, 1))  # Add a random jitter
            delay = min(delay * 2, MAX_DELAY)
            retries += 1

    return False


#########################
##### Cache and KB #####
#######################

def put_validity_cloudformation(sessionId, template, is_valid):
    """
    Stores the validity of a CloudFormation template in DynamoDB.

    Args:
        sessionId (str): The ID of the session.
        template (str): The CloudFormation template.
        is_valid (bool): Whether the template is valid or not.

    Returns:
        bool: True if the validity is stored successfully, False otherwise.
    """
    try:
        creationDate = str(
            int(datetime.datetime.now(tz=datetime.timezone.utc).timestamp())
        )
        ttl = str(
            int((datetime.datetime.now() + datetime.timedelta(seconds=900)).timestamp())
        )

        response = table.update_item(
            Key={"sessionId": sessionId, "version": "v0"},
            # Atomic counter is used to increment the latest version
            UpdateExpression="SET Latest = if_not_exists(Latest, :defaultval) + :incrval, #creationDate = :creationDate, #template = :template, #ttl = :ttl",
            ExpressionAttributeNames={
                "#creationDate": "creationDate",
                "#template": "template",
                "#ttl": "ttl",
                "#is_valid": "is_valid"
            },
            ExpressionAttributeValues={
                ":creationDate": creationDate,
                ":is_valid": is_valid,
                ":template": template,
                ":ttl": ttl,
                ":defaultval": 0,
                ":incrval": 1,
            },
            # return the affected attribute after the update
            ReturnValues="UPDATED_NEW",
        )

        # Get the updated version
        latest_version = response["Attributes"]["Latest"]

        # Add the new item with the latest version
        table.put_item(
            Item={
                "sessionId": sessionId,
                "is_valid": is_valid,
                "version": "v" + str(latest_version),
                "creationDate": creationDate,
                "template": template,
                "ttl": ttl,
            }
        )
    except Exception as ex:
        print(f"Error at put_generated_cloudformation {ex}")
        return False
    else:
        return True

def put_generated_cloudformation(sessionId, template):
    """
    Stores the generated CloudFormation template in DynamoDB.

    Args:
        sessionId (str): The ID of the session.
        template (str): The generated CloudFormation template.

    Returns:
        bool: True if the template is stored successfully, False otherwise.
    """
    try:
        creationDate = str(
            int(datetime.datetime.now(tz=datetime.timezone.utc).timestamp())
        )
        ttl = str(
            int((datetime.datetime.now() + datetime.timedelta(seconds=900)).timestamp())
        )

        response = table.update_item(
            Key={"sessionId": sessionId, "version": "v0"},
            # Atomic counter is used to increment the latest version
            UpdateExpression="SET Latest = if_not_exists(Latest, :defaultval) + :incrval, #creationDate = :creationDate, #template = :template, #ttl = :ttl",
            ExpressionAttributeNames={
                "#creationDate": "creationDate",
                "#template": "template",
                "#ttl": "ttl",
            },
            ExpressionAttributeValues={
                ":creationDate": creationDate,
                ":template": template,
                ":ttl": ttl,
                ":defaultval": 0,
                ":incrval": 1,
            },
            # return the affected attribute after the update
            ReturnValues="UPDATED_NEW",
        )

        # Get the updated version
        latest_version = response["Attributes"]["Latest"]

        # Add the new item with the latest version
        table.put_item(
            Item={
                "sessionId": sessionId,
                "version": "v" + str(latest_version),
                "creationDate": creationDate,
                "template": template,
                "ttl": ttl,
            }
        )
    except Exception as ex:
        print(f"Error at put_generated_cloudformation {ex}")
        return False
    else:
        return True


def get_generated_cloudformation(sessionId, version="v0"):
    """
    Retrieves the generated CloudFormation template from DynamoDB.

    Args:
        sessionId (str): The ID of the session.
        version (str): The version of the template to retrieve.

    Returns:
        str: The generated CloudFormation template.
    """
    return table.get_item(Key={"sessionId": sessionId, "version": version})["Item"][
        "template"
    ]


def get_kb_yaml(sessionId, version="METADATA"):
    """
    Retrieves the YAML metadata from DynamoDB.

    Args:
        sessionId (str): The ID of the session.
        version (str): The version of the metadata to retrieve.

    Returns:
        dict: The YAML metadata.
    """
    return table.get_item(Key={"sessionId": sessionId, "version": version})


def retrieve_relevant_documents(sessionId, query):
    """
    Retrieves relevant documents from the knowledge base.

    Args:
        sessionId (str): The ID of the session.
        query (str): The query to search for relevant documents.

    Returns:
        dict: The relevant documents.
    """
    creationDate = str(int(datetime.datetime.now(tz=datetime.timezone.utc).timestamp()))
    ttl = str(
        int((datetime.datetime.now() + datetime.timedelta(seconds=900)).timestamp())
    )

    relevant_documents = bedrock_agent.retrieve(
        retrievalQuery={"text": get_summary_document(query)},
        knowledgeBaseId=KnowledgeBaseId,
        retrievalConfiguration={
            "vectorSearchConfiguration": {
                "numberOfResults": 3,
                "overrideSearchType": "HYBRID",
            }
        },
    )

    for idx, metadata in enumerate(
        [result["metadata"] for result in relevant_documents["retrievalResults"]]
    ):

        response = table.update_item(
            Key={"sessionId": sessionId, "version": "METADATA"},
            UpdateExpression=f"SET #document{idx} = :document{idx}, #creationDate = :creationDate, #ttl = :ttl",
            ExpressionAttributeNames={
                f"#document{idx}": f"document{idx}",
                "#creationDate": "creationDate",
                "#ttl": "ttl",
            },
            ExpressionAttributeValues={
                f":document{idx}": metadata,
                ":creationDate": creationDate,
                ":ttl": ttl,
            },
            # return the affected attribute after the update
            ReturnValues="ALL_NEW",
        )
    return response["Attributes"]


def retrieve_yaml(sessionId, query=None):
    """
    Retrieves the yaml from DynamoDB if it exists there, or from the knowledge base if the metadata is not found in DynamoDB.

    Args:
        sessionId (str): The ID of the session.
        query (str): The query to search for relevant documents.

    Returns:
        dict: The YAML metadata.
    """
    response = get_kb_yaml(sessionId=sessionId, version="METADATA")

    if "Item" in response:
        relevant_documents = response["Item"]
        print(f"Found item in dynamodb {sessionId}")
    else:
        print(f"Item with key {sessionId} not found.")
        relevant_documents = retrieve_relevant_documents(
            sessionId=sessionId, query=query
        )

    documents = list()

    for docs in [v for k, v in relevant_documents.items() if "document" in k]:
        bucket, key = docs["cfn_stack"].replace("s3://", "").split("/", 1)

        try:
            # Retrieve the object contents
            response = s3.get_object(Bucket=bucket, Key=key)
            contents = response["Body"].read().decode("utf-8")
            documents.append(contents)
        except ClientError as e:
            if e.response["Error"]["Code"] == "NoSuchKey":
                print("The specified object does not exist.")
            else:
                print(f"An error occurred: {e}")

    return documents


###############################
##### Utility Functions  #####
#############################


def get_new_architecture_explaination(architectureExplanation, updateInstruction):
    """
    Generating new architecture explaination integration update instruction.

     Args:
         architectureExplanation (str): Current architecture explanation.
         updateInstruction (str): Update instruction to update current CloudFormation template.

     Returns:
         str: New architecture explanation.
    """

    _system_prompt = """
        List all the AWS Services in the document. Do output anything else.
    """
    _prompt = f"""
        <para1>
        {architectureExplanation}
        </para1>

        <para2>
        {updateInstruction}
        </para2>
    """

    _messages = [{"role": "user", "content": [{"text": _prompt}]}]
    # func, modelId, system_prompt, messages
    return backoff_mechanism(
        func=invoke_model,
        modelId=summary_modelId,
        system_prompt=_system_prompt,
        messages=_messages,
    )


def get_summary_document(explain):
    """
    Generating an explanation with less than 1000 characters to accommodate the character limit for the knowledge base query.

    Args:
        explain (str): Current architecture explanation recieved from the streamlit app.

    Returns:
        str: New architecture explanation with less than 1000 characters.
    """
    _system_prompt = """
        List all the AWS Services in the document. Do output anything else.
    """
    _prompt = f"""
        <document>
        {explain}
        </document>

    """
    _messages = [{"role": "user", "content": [{"text": _prompt}]}]
    # func, modelId, system_prompt, messages
    return backoff_mechanism(
        func=invoke_model,
        modelId=summary_modelId,
        system_prompt=_system_prompt,
        messages=_messages,
    )


#########################
##### Generate CFN #####
#######################


def generate_cloudformation(architectureExplanation, sessionId):
    """
    Generates a CloudFormation template from an architecture explanation. Stores this generated template in DynamoDB.

    Args:
        event (dict): The event data.

    Returns:
        bool: Indicating if the template was generated successfully.
    """
    try:
    
        documents = retrieve_yaml(
            sessionId=sessionId, query=architectureExplanation
        )
    
        _system_prompt = """
            You are an expert AWS CloudFormation developer. Your task is to convert instuctions to valid CloudFormation template in YAML format.
            Accept step-by-step explaination of the AWS Architecture encapsulated between <explain></explain> XML tags and generate its CloudFormation code. 
        """
    
        _prompt = f"""
                
            Create CLoudFormation code only for AWS Servies present in <explain></explain>
            
            <explain>
            {architectureExplanation}
            </explain>
            
            - Mimic the practices of example CloudFormation templates given between <example></example> XML tags.
            - Use AWS CloudFormaton Pseudo parameters where necessary.
            - Use structure of example templates.
            
            Do not return examples or explaination, only return the generated CloudFormation YAML template without ```yaml ```. Skip the preamble. Think step-by-step.
    
        """
        message_document = [
            {
                "role": "user",
                "content": [
                    {
                        "text": f"""Take this example CloudFormation YAML code as a refernce <example{idx}></example{idx}>:
                            <example{idx}>
                                {document}
                            </example{idx}>
                            """,
                    }
                    for idx, document in enumerate(documents)
                ],
            }
        ]
        message_document[0]["content"].append(
            {
                "text": _prompt,
            },
        )
        _messages = message_document
    except Exception as ex:
        return False, ex
    else:
        # func, modelId, system_prompt, messages
        generated_cloudformation_stack = backoff_mechanism(
            func=invoke_model,
            modelId=generate_modeId,
            system_prompt=_system_prompt,
            messages=_messages,
        )
    
        if not generated_cloudformation_stack:
            return False, f"Bedrock call was unsuccessful"
    
        if put_generated_cloudformation(
            sessionId=sessionId, template=generated_cloudformation_stack
        ):
            return True, {'CloudformationTemplate': True}
        else:
            return False, f"Template storage unsuccessful"


#########################
##### Validate CFN #####
#######################


def validate_cloudformtaion(sessionId):
    """
    Validates the CloudFormation template stored in version vo (latest) in DynamoDB.

    Args:
        event (dict): The event data.

    Returns:
        dict: {"isValid": True/False, "error": Error Message}
    """
    try:
        cloudformationTemplate = get_generated_cloudformation(sessionId=sessionId)
    except Exception as ex:
        return False, ex

    validation_errors = str()
    try:
        response = cfn.validate_template(
            TemplateBody=cloudformationTemplate,
        )
    except ValidationError as ex:
        print(f"Cloudformation template invalid: {ex}")
        validation_errors = f"Cloudformation template invalid: {ex}"
        is_valid = False
    except Exception as ex:
        return False, ex
    else:
        is_valid = True
        print("Cloudformation valid")

    if put_validity_cloudformation(sessionId=sessionId, template=cloudformationTemplate, is_valid=is_valid):
        return True, {"isValid": is_valid, "error": str(validation_errors)}
    else:
        return False, f"Template storage unsuccessful"
        

##########################
##### Reiterate CFN #####
########################


def reiterate_cloudformation(architectureExplanation, sessionId):
    """
    Reiterates the CloudFormation template stored in version vo (latest) in DynamoDB. Stores the new generated template in DynamoDB.

    Args:
        event (dict): The event data.

    Returns:
        bool: Indicating if the template was generated successfully.
    """
    try:

        cloudformationTemplate = get_generated_cloudformation(
            sessionId=sessionId
        )

        documents = retrieve_yaml(
            query=architectureExplanation,
            sessionId=sessionId,
        )
        _system_prompt = f"""
            You are an AWS CloudFormation expert and a master of AWS best practices. 
            Your task is to review CloudFormation template provided between <cloudformation></cloudformation> XML tags and iteratively enhance them to align with AWS recommendations and guidelines. 

            To guide you, user will provide examples encapsulated within <example></example> XML tags. These examples will showcase AWS best practices and brand voice in action, allowing you to understand and apply them effectively.

            Your output should be a revised version of the provided CloudFormation template, incorporating AWS best practices and brand voice.
        """
        _prompt = f"""
            Reiterate the CloudFormation template.
            
            <cloudformation>
                {cloudformationTemplate}
            </cloudformation>
            
            Do not return examples or explaination, only return the generated CloudFormation YAML template without ```yaml ```. Skip the preamble. Think step-by-step. 
        """

        message_document = [
            {
                "role": "user",
                "content": [
                    {
                        "text": f"""Take this example CloudFormation YAML code as a refernce <example{idx}></example{idx}>:
                            <example{idx}>
                                {document}
                            </example{idx}>
                            """,
                    }
                    for idx, document in enumerate(documents)
                ],
            }
        ]

        message_document[0]["content"].append(
            {
                "text": _prompt,
            },
        )
        _messages = message_document
    except Exception as ex:
        return False, ex
    else:
        # func, modelId, system_prompt, messages

        updated_cloudformation = backoff_mechanism(
            func=invoke_model,
            modelId=generate_modeId,
            system_prompt=_system_prompt,
            messages=_messages,
        )
        if not updated_cloudformation:
            return False, f"Bedrock call was unsuccessful"

        if put_generated_cloudformation(sessionId=sessionId, template=updated_cloudformation):
            return True, {"reiteratedCloudformationTemplate": True}
        else:
            return False, "Template storage unsuccessful"


#######################
##### Update CFN #####
#####################


def update_cloudformation(updateInstruction, architectureExplanation, sessionId):
    """
    Updates the CloudFormation template stored in version vo (latest) in DynamoDB. Stores the new generated template in DynamoDB.

    Args:
        event (dict): The event data.

    Returns:
        bool: Indicating if the template was generated successfully.
    """
    try:

        cloudformationTemplate = get_generated_cloudformation(
            sessionId=sessionId
        )
        table.delete_item(
            Key={
                "sessionId": sessionId,
                "version": "METADATA",
            },
        )
        newArchitectureExplanation = get_new_architecture_explaination(
            architectureExplanation, updateInstruction
        )

        if not newArchitectureExplanation:
            return False, "Could not generate new architecture explanation"

        documents = retrieve_yaml(
            sessionId=sessionId, query=newArchitectureExplanation
        )

        _system_prompt = """
            You are an expert AWS CloudFormation developer tasked with updating CloudFormation code given in YAML format.
            
            1. You will receive the update instruction in <update></update> and will need to update the CloudFormation code in <cloudformation></cloudformation>.
            2. You will be provided with example AWS CloudFormation between <example></example> XML tags for reference. 
            
            Please note that you should not make any changes to the code until you receive specific instructions from the user. Your role is to accurately interpret the user's requirements and modify the CloudFormation YAML code accordingly.
        """
        _prompt = f"""
        
        I need your assistance in updating AWS CloudFormation template. Please review the following:

        <cloudformation>
        {cloudformationTemplate}
        </cloudformation>
        
        <update>
        {updateInstruction}
        </update>
                

        Once you have completed the updates, you will output only the revised CloudFormation YAML template without ```yaml ```. Skip the preamble.Think step-by-step. 
        """
        message_document = [
            {
                "role": "user",
                "content": [
                    {
                        "text": f"""Take this example CloudFormation YAML code as a refernce <example{idx}></example{idx}>:
                            <example{idx}>
                                {document}
                            </example{idx}>
                            """,
                    }
                    for idx, document in enumerate(documents)
                ],
            }
        ]

        message_document[0]["content"].append(
            {
                "text": _prompt,
            },
        )
        _messages = message_document
    except Exception as ex:
        return False, ex
    else:

        # func, modelId, system_prompt, messages

        updated_cloudformation = backoff_mechanism(
            func=invoke_model,
            modelId=generate_modeId,
            system_prompt=_system_prompt,
            messages=_messages,
        )
        if not updated_cloudformation:
            return False, "Bedrock call was unsuccessful"
        
        if put_generated_cloudformation(sessionId=sessionId, template=updated_cloudformation):
            return True, {"updatedCloudformationTemplate": True}
        else:
            return False, "Template storage unsuccessful"


##########################
##### Resolve Error #####
########################


def resolve_cloudformation(error, architectureExplanation, sessionId):
    """
    Resolves the error message stored in version vo (latest) in DynamoDB. Stores the new generated template in DynamoDB.

    Args:
        event (dict): The event data.

    Returns:
        bool: Indicating if the template was generated successfully.
    """
    try:

        cloudformationTemplate = get_generated_cloudformation(
            sessionId=sessionId
        )

        documents = retrieve_yaml(
            sessionId=sessionId, query=architectureExplanation
        )
        _system_prompt = """
        You are an AWS CloudFormation expert skilled in analyzing and troubleshooting CloudFormation templates. Your task is as follows:

        1. Review the provided CloudFormation template between <cloudformation></cloudformation> and error message <error></error> carefully.
        2. Identify the root cause of the error in the template.
        3. Provide a corrected version of the CloudFormation template that resolves the issue.

        To ensure a high-quality response, please:

        - Thoroughly understand the error message and its context within the template.
        - Leverage examples provided between <example></example> XML tags.
        - Validate the corrected template to ensure it resolves the error.

        Your expertise in troubleshooting CloudFormation templates is crucial for delivering an accurate and actionable solution.
        """

        _prompt = f"""
        I need your assistance in troubleshooting an issue with an AWS CloudFormation template. Please review the following:

        <cloudformation>
        {cloudformationTemplate}
        </cloudformation>

        <error>
        {error}
        </error>
        
        Once you have completed the updates, you will output only the revised CloudFormation YAML template without ```yaml ```. Skip the preamble. Think step-by-step. 
        """

        message_document = [
            {
                "role": "user",
                "content": [
                    {
                        "text": f"""Take this example CloudFormation YAML code as a refernce <example{idx}></example{idx}>:
                            <example{idx}>
                                {document}
                            </example{idx}>
                            """,
                    }
                    for idx, document in enumerate(documents)
                ],
            }
        ]

        message_document[0]["content"].append(
            {
                "text": _prompt,
            },
        )
        _messages = message_document
    except Exception as ex:
        return False, ex
    else:
        # func, modelId, system_prompt, messages

        updated_cloudformation = backoff_mechanism(
            func=invoke_model,
            modelId=generate_modeId,
            system_prompt=_system_prompt,
            messages=_messages,
        )
        if not updated_cloudformation:
            return False, "Bedrock call was unsuccessful"
        if put_generated_cloudformation(sessionId=sessionId, template=updated_cloudformation):
            return True, {"updatedCloudformationTemplate": True}
        else:
            return False, "Template storage unsuccessful"


###########################
##### Lambda Handler #####
#########################


def lambda_handler(event, context):
    print(event)

    response_code = 200
    action_group = event["actionGroup"]
    api_path = event["apiPath"]
    http_method = event["httpMethod"]
    parameters = event.get('parameters', [])
    if api_path == "/generateCloudFormation":
        
        for param in parameters:
            if param['name'] == 'architectureExplanation':
                architectureExplanation = param['value']
                
        if not architectureExplanation:
            raise Exception("Missing mandatory parameter: architectureExplanation")
        
        valid, result = generate_cloudformation(architectureExplanation=architectureExplanation, sessionId=event["sessionId"])
        
    elif api_path == "/validateCloudFormation":
        
        valid, result = validate_cloudformtaion(sessionId=event["sessionId"])
        
    elif api_path == "/reiterateCloudFormation":
        for param in parameters:
            if param['name'] == 'architectureExplanation':
                architectureExplanation = param['value']
                
        if not architectureExplanation:
            raise Exception("Missing mandatory parameter: architectureExplanation")
        
        valid, result = reiterate_cloudformation(architectureExplanation=architectureExplanation, sessionId=event["sessionId"])
        
    elif api_path == "/updateCloudFormation":
         
        for param in parameters:
            if param['name'] == 'updateInstruction':
                updateInstruction = param['value']
            if param['name'] == 'architectureExplanation':
                architectureExplanation = param['value']
        
        if not architectureExplanation:
            raise Exception("Missing mandatory parameter: architectureExplanation")
        
        if not updateInstruction:
            raise Exception("Missing mandatory parameter: updateInstruction")
        
        valid, result = update_cloudformation(updateInstruction=updateInstruction, architectureExplanation=architectureExplanation, sessionId=event["sessionId"])
    elif api_path == "/resolveCloudFormation":
        for param in parameters:
            if param['name'] == 'error':
                error = param['value']
            if param['name'] == 'architectureExplanation':
                architectureExplanation = param['value']
        
        if not architectureExplanation:
            raise Exception("Missing mandatory parameter: architectureExplanation")
        
        if not error:
            raise Exception("Missing mandatory parameter: error")
        
        valid, result = resolve_cloudformation(error=error, architectureExplanation=architectureExplanation, sessionId=event["sessionId"])
    else:
        raise Exception(f"Unrecognized api path: {action_group}::{api_path}")
        
    
    if not valid:
        raise Exception(f"Api path {action_group}::{api_path} returned an error: {error}")

    response_body = {"application/json": {"body": result}}

    action_response = {
        "actionGroup": action_group,
        "apiPath": api_path,
        "httpMethod": http_method,
        "httpStatusCode": response_code,
        "responseBody": response_body,
    }

    api_response = {"messageVersion": "1.0", "response": action_response}
    return api_response
